### ISSUE TITLE
Backend Signin response type

### ISSUE THREAD

**Issue by bwqr** [bounswe/bounswe2019group6#100]
Currently, `/users/signin` endpoint returns a bare string on success, which is not a valid JSON. On the android side, i am having trouble while parsing this input. Can we wrap this bare string into a JSON like 
`{"token":"etc"}`.

**Comment by enozcan** [comment]
Hi @bwqr 
That definitely makes sense. I'm on it.
Thanks for the feedback.

**Comment by enozcan** [comment]
I've just fixed and sent a PR. After @burakikanyildiz and @barisegesevgili reviews we can merge to the master.

**Comment by bwqr** [comment]
Thanks for your efforts. This issue can be closed after PR merged.

**Comment by enozcan** [comment]
Done in #105
