### ISSUE TITLE
About Actions Table in Meeting Notes

### ISSUE THREAD

**Issue by cmpe250test** [bounswe/bounswe2019group6#107]
Dear Group 6,

While writing your meeting notes, rather than having repeated actions for different assignees, you can have a single action with multiple assignees (e.g., Action 1-3, 4-6, 7-9, and 10-12 in [Meeting Notes #11](https://github.com/bounswe/bounswe2019group6/wiki/Meeting-Notes-%2311)).

**Comment by mericturan** [comment]
Oppps, I accidentally posted this issue with the wrong account :-)

**Comment by sadullahgultekin** [comment]
Okay, we have updated previous week's meeting notes and we will keep writing in that way
