### ISSUE TITLE
Improper HTTP responses and messages

### ISSUE THREAD

**Issue by enozcan** [bounswe/bounswe2019group6#115]
There are still some unhandled exceptions which return generic error response with generic error message. This makes android and frontend debugging so hard and hence exceptions have to be specified in terms of both status code and message.

**Comment by barisegesevgili** [comment]
I have specified status codes of the exception with my latest commit. We can close the issue

https://github.com/bounswe/bounswe2019group6/commit/0992d89c3920e4a916a342a85f0e202d0938f125
