### ISSUE TITLE
API Update For Profile Info

### ISSUE THREAD

**Issue by sadullahgultekin** [bounswe/bounswe2019group6#126]
In the profile page, we get some info for a user but I think it is not enough.

For example we have latitude and longitude information, but we cannot show that in a profile page. We need something like city name or county name as a location so that we can use it in a profile page. 

We also need a profile image. For now backend can just return a default image, we can improve it in the future.

Other necessary information that can be shown are "follower number", "following number", "article number", "comment number" ...

**Comment by enozcan** [comment]
Do you have idea if there is a service like "from coordinates to place name" by Google or Yandex or something else for js?  I recommend not to make user able to enter place names since this might make location based searching harder i.e. when two users enter "istanbul" and "İstanbul" for the same place.

**Comment by sadullahgultekin** [comment]
I think most of the group members think that we need to make user to select a point in a map to give a location information, or we need to take a latitude and longitude information as a two number. However, I think forcing user to do that is insensible. I can't think of an application that obliges me to give latitude and longitude information by hand.

I think we need a search bar that user can enter his/her location, and while user enters some character we can use google maps api to give some location suggestions. We can do it in the frontend or in the backend. For now I don't know which one is easier but as far as I remember in the last semester @bwqr made an api that uses a functionality like we want now.

We need to consider android team as well. If we decide to make a search bar, will it be problem for them?

@bwqr can you help us in these decisions?

**Comment by enozcan** [comment]
The point of latitude & longitude storage of location data is to fetch user's location directly from a map view (Google Maps may be) and then send that directly to server. So make a user enter numeric values for a location was not expected. However, IMO, if we want to store city / country data then we have to make sure that those names will be the same for a particular location. For instance, there must be only one mark for `Istanbul`, not `Sariyer, Istanbul` or `Tuzla mh., Istanbul` etc. and both frontend and android side must ensure that.

**Comment by barisegesevgili** [comment]
As a member of group6, In my opinion city information is the only info that should be gathered. If there is an API which directly determines the city info from GPS of the user, it is enough for us. But for sure, we dont make a user enter the location information by hand(GPS must be used for reliability purposes)

**Comment by sadullahgultekin** [comment]
After talking to the customer, we decided to show a map to the user in the registration page. We will get a point on the map, and use that info in our system.
