### ISSUE TITLE
http status codes for follow

### ISSUE THREAD

**Issue by barisegesevgili** [bounswe/bounswe2019group6#127]
Currently response code for trying to follow a user that the user already follows is 500, shouldnt it be 403? @burakikanyildiz @enozcan

**Comment by enozcan** [comment]
We should avoid sending 500 for non internal error cases. Returning 500 means that the request is valid but server was not able to handle that. However for the case you pointed out this is not related to an internal error. Also 403 is not proper as well (this is not an unauthorized case.). IMO `406 Not Acceptable` is the proper one.

**Comment by barisegesevgili** [comment]
Agreed in my side! If you also agree I can correct the related response @burakikanyildiz

**Comment by burakikanyildiz** [comment]
I agree with you mates. Not acceptable seems more relevant with this issue. However, I think this is not the only problem about HTTP responses. Several other endpoints also needs to be improved in terms of HTTP responses.

**Comment by barisegesevgili** [comment]
what about 

- 417 Expectation Failed

The expectation given in an Expect request-header field could not be met by this server, or, if the server is a proxy, the server has unambiguous evidence that the request could not be met by the next-hop server.

- 412 Precondition Failed

The precondition given in one or more of the request-header fields evaluated to false when it was tested on the server. This response code allows the client to place preconditions on the current resource metainformation (header field data) and thus prevent the requested method from being applied to a resource other than the one intended.

where suggested response definiton of 409 is

- 403 Forbidden

The server understood the request, but is refusing to fulfill it. Authorization will not help and the request SHOULD NOT be repeated. If the request method was not HEAD and the server wishes to make public why the request has not been fulfilled, it SHOULD describe the reason for the refusal in the entity. If the server does not wish to make this information available to the client, the status code 404 (Not Found) can be used instead.

**Comment by barisegesevgili** [comment]
I think 412 is the most proper one, wrt my further researches
