### ISSUE TITLE
(front-end) Implementing features related to User Follow/Following facility 

### ISSUE THREAD

**Issue by barisegesevgili** [bounswe/bounswe2019group6#133]
All endpoints can be found from the latest deployment. For further details and needs pls contact.

-user can follow/unfollow a user

-user can get all of his/her followers and followings and related numbers

**Comment by sadullahgultekin** [comment]
We have implemented these functionalities. For now, if you want to see the working version please look to `frontend-profile` branch. Later, we will add this to master branch and make the deployment
