### ISSUE TITLE
Error Response Messages

### ISSUE THREAD

**Issue by burakyuksel0** [bounswe/bounswe2019group6#145]
With the latest update, error messages are configured as response's **message** field. As far as I see, the current error response messages for user related requests are correct and meaningful. I wanted to inform backend team about the update. Please, keep adding appropriate messages to responses for upcoming endpoints and update existing error response messages that do not match with error.
Thanks.

**Comment by burakikanyildiz** [comment]
Hello @burakyuksel0, thank you for your feedback. We are working on improving error responses. Stay tuned!

**Comment by enozcan** [comment]
@burakyuksel0 we will consider this.  
Since that is kind of suggestion to backend team and not an issue to be solved, closing this.
