### ISSUE TITLE
Api update

### ISSUE THREAD

**Issue by sadullahgultekin** [bounswe/bounswe2019group6#159]
I am trying to add follow functionality. When I try to follow a user, I send a request to `/follow/unfollow_user` endpoint and I get this error. Apparently the message is wrong. Can you fix it?

When we finalize the user following system, we won't show this message to the user, but still we need to change it.

![Screen Shot 2019-11-08 at 01 47 43](https://user-images.githubusercontent.com/16756389/68434419-f6451c00-01c9-11ea-9ade-da16a2f01836.png)

**Comment by bwqr** [comment]
I think, the problem lay under the endpoint you are trying to reach. To follow a user, you should send the request to `/follow/follow_user`,

**Comment by barisegesevgili** [comment]
Just as Fatih stated above, I checked it again and there is no problem about endpoint and related message.
