### ISSUE TITLE
Follow Requirements does not match

### ISSUE THREAD

**Issue by bwqr** [bounswe/bounswe2019group6#160]
Hi there, I have found out a bug about following a user.

### Expected Behavior

The users whose profile are public, should be followed immediately without pending the user approval.  

### Current Behavior

Whether user's profile is public or private, approval is needed.

### Possible Solution

Allow direct follow if the user's profile is public.

### Steps to Reproduce

1. Set your profile to public
2. Send from another user a follow request.
3. See the pending follow request.

### Detailed Description

This bug violates the requirement 
`1.1.3.1. User shall be able to follow other users directly if the user's profile is public.`
### Possible Implementation
<!--- Not obligatory, bu

**Comment by barisegesevgili** [comment]
We are aware of the situation you have mentioned.  It will be implemented according to the related requirements, and considering the priority.

Thanks for informing us!

**Comment by barisegesevgili** [comment]
The related function is corrected as stated in Project requirements and merged into backend-dev.
