### ISSUE TITLE
[Backend] User Profile endpoint, wrong follower and following numbers.

### ISSUE THREAD

**Issue by bwqr** [bounswe/bounswe2019group6#173]
Hi there, I think there is a wrong mapping in the `users/me` end point. Correct me if I am wrong.

### Expected Behavior

`followersCount` field should represent the followers who are following the current user and `followingsCount` field should represent following who are followed by current user.
### Current Behavior

These two fields are interchanged.

### Possible Solution

Interchange them.

### Steps to Reproduce

1. Send a follow request to another user.
2. Sign in as follow request sent user.
3. Inspect the `users/me` endpoint and observe the `followersCount` and `followingsCount` fields.

### Possible Implementation
<!--- Not obligatory, bu

**Comment by enozcan** [comment]
Thanks for reporting. Fixed and deployed on 72c44bc
