### ISSUE TITLE
Create Glossary Page

### ISSUE THREAD

**Issue by enozcan** [bounswe/bounswe2019group6#18]

**Comment by bwqr** [comment]
Words are defined. Review is needed.

**Comment by bwqr** [comment]
Definitions are added. Some words need to be discussed about adding into glossary.

**Comment by burakikanyildiz** [comment]
Please update and modify the glossary page according to feedback until 28/02/2019.

**Comment by bwqr** [comment]
Listing types are updated, reviewed according to feedback
