### ISSUE TITLE
Deciding on "News" Endpoints

### ISSUE THREAD

**Issue by barandenizkorkmaz** [bounswe/bounswe2019group6#183]
Hi Folks,
Just as @bwqr stated earlier, same issue applies for the case of News feature. I'm asking from the backend team if they can make an abstraction about the endpoints of the news and what data they should include. 
Good Work!

**Comment by enozcan** [comment]
Hi @barandenizkorkmaz 

AFAIK there was no news part in the project description from the last semester and added laterly. Thus we may remove the news part from the project. What do you think about that @burakikanyildiz @barisegesevgili ?

**Comment by barisegesevgili** [comment]
IMO we should make this decision all team-wide, instead of just backend-team. We need to discuss it on next meeting all-together

**Comment by barandenizkorkmaz** [comment]
We have mentioned in the project requirements as follows:
1.1.9. News Section
1.1.9.1. Users shall be able to see news fetched from third party website.
1.1.9.2. Users shall be able to see news written by other users.
1.1.10.1. Users should be able to be redirected to third party site when click the news they would like to read in detail.

In the project description, it seems that it's not a must. If that is okay for you, let us delaying the implementation of the news section even if we decide adding it as an extra feature.

**Comment by barisegesevgili** [comment]
Deal, closing the issue then for now
