### ISSUE TITLE
update getAll endpoint

### ISSUE THREAD

**Issue by sadullahgultekin** [bounswe/bounswe2019group6#189]
In the `user/getAll` endpoint, we get all users that are registered to our system. I use this result to render the search page. However there are some users that shouldn't be given in the response. This user type is the user who have tried to register our system but didn't do the e-mail verification. A user shouldn't be able to get this user's information, or follow him/her. So, can you update the endpoint such that it doesn't return non-validated users?

**Comment by barisegesevgili** [comment]
Currently, if the stated user is not validated, follow endpoint already does not let anybody follow him/her. On the other side, we'll correct the stated behavior. Thx for informing

**Comment by enozcan** [comment]
Thanks for the feedback.
Fixed on 6cebf59 and will be deployed soon.
