### ISSUE TITLE
[Frontend] Design update to trading equipment page

### ISSUE THREAD

**Issue by sadullahgultekin** [bounswe/bounswe2019group6#198]
Hi @irmakguzey,

In the trading equipment page, we have our label on the left side of the graph. I think moving it to upper side of the graph may seem more beautiful. We can try both of them if you want and see the difference.

This is a design choice, both of them will do fine, you are the one who implemented it, so its your choice. After the Milestone II though, we can re-implement it and discuss together.

**Comment by irmakguzey** [comment]
Hey @sadullahgultekin , 
With the PR #271, I believe this issue is solved. Could you take a look and close this issue if this is case? 
Thanks a lot btw for opening this issue! :)
