### ISSUE TITLE
Bug while retrieving user's own transactions.

### ISSUE THREAD

**Issue by burakikanyildiz** [bounswe/bounswe2019group6#200]
According to feedback that android team give, there is a bug while getting the own transactions of requester in the endpoints  **transactions/count/user/{username} and transactions/user/{username}**

**Comment by burakikanyildiz** [comment]
@bwqr I have fixed the problem. Could you please try the last version of backend-dev and let me know if there is any issue.

**Comment by bwqr** [comment]
@burakikanyildiz just checked and works as expected, thanks for fixing it quickly.
