### ISSUE TITLE
Deposit Currency Type

### ISSUE THREAD

**Issue by sadullahgultekin** [bounswe/bounswe2019group6#217]
Hello @burakikanyildiz , 
Currently we have an endpoint called `/investment/deposit` to load a money to the system. There isn't any information about what we load to our account, USD? or TL? or any other currency type?
I think the user should be able to load 2 or 3 type of currency to his/her account. What do you think? 
This is not an urgent issue. After the MS 2 we can implement it if we decide to do.

**Comment by burakikanyildiz** [comment]
As we have discussed in the meetings, it's USD for now. And all other functionalities of TraderX are also using USD as base currency. However, as backend team, we have not implemented it in a hardcoded way. We think providing user option that s/he can change his/her base currency in the future but as i said now it now uses USD as base and we can discuss extending it after MS2 if it's also okey to you

**Comment by sadullahgultekin** [comment]
If you think about it, it's okey for me. As you said we can handle it after MS2.
Thank you!
