### ISSUE TITLE
Password requirements

### ISSUE THREAD

**Issue by burakyuksel0** [bounswe/bounswe2019group6#249]
Hi,

Passwords are required to contain a special character. Currently, the list of special characters are 
- [**@**,**#**,**$**,**%**,**^**,**&**,**+**,**=**]

I think we need to add two more characters to this list:
- Underscore (_)
- Dot (.)

I remember talking this with Meriç. Making this modification will be very easy on our side. Let me know if this will cause a problem for backend and/or android.

And please specify if any other characters you may want to add to the list come to your mind.

Thanks.

**Comment by bwqr** [comment]
Well, after implementing lots of features, changing some basic operations are not worthed to do. For android team, I think no problem will occur. If backend team also thinks like you, change can be made.

**Comment by enozcan** [comment]
It’s also OK on backend side. We can change it on the next deployment.

**Comment by enozcan** [comment]
Updated on 1120f26.

New password regex is the following:

```regex
^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=_.])(?=\S+$).{6,}$
```
