### ISSUE TITLE
[Frontend] Add Article List, Comments and Alert Features to Trading Equipment Detailed Page

### ISSUE THREAD

**Issue by irmakguzey** [bounswe/bounswe2019group6#250]
We would like to add creating/seeing alerts, writing/seeing comments and a list of articles in the detailed page for each of the trading equipment. These features to be added to the detailed page of the trading equipment. 
According to the last team meeting alert related implementations are assigned to @burakyuksel0 and the rest of it is assigned to me.

**Comment by irmakguzey** [comment]
Article List is added with the Pull Request #251.

**Comment by irmakguzey** [comment]
Comments are added and connected to the backend with the Pull Request #252

**Comment by burakyuksel0** [comment]
Alerts are added and connected to the backend with #314.

**Comment by irmakguzey** [comment]
With the #317 article list is removed from the detailed page and the reason behind it is explained as 

> According to our last discussion, and regarding the issue #250 we decided to remove the article list from the detailed page considering the fact that it requires active use of tags which is not that case for our system currently.

And with the last PR merged, this issue is now closed.
