### ISSUE TITLE
Comments should be modified in a way that they can be liked

### ISSUE THREAD

**Issue by burakikanyildiz** [bounswe/bounswe2019group6#254]
Hello @enozcan , since you have implemented comments system, I am assigning this issue to you. 
After my discussions with frontend and android teams, we have decided that comments should be likeable and likes can be taken back by user who liked, and also we should store the persons who liked in order to show them. If you have any further questions, we can talk under this issue. Also, if anything helpful that I can do for comments, don't hesitate to ask.

**Comment by enozcan** [comment]
Implemented in #255

**Comment by burakikanyildiz** [comment]
Thank you @enozcan . I will review your pr asap.

**Comment by enozcan** [comment]
Merged #255
