### ISSUE TITLE
Bug report to "/portfolio/add" endpoint

### ISSUE THREAD

**Issue by sadullahgultekin** [bounswe/bounswe2019group6#263]
I am trying to link "add equipment to portfolio" functionality. I am getting an error, but I couldn't understand the reason. I thought that maybe there is a bug in the backend, so I am creating this issue. 

I checked the api from postman, I add the screenshots below, can you check it?

![Screen Shot 2019-12-12 at 10 32 54](https://user-images.githubusercontent.com/16756389/70692224-ebe7d780-1ccb-11ea-8954-e1aad86c592e.png)
![Screen Shot 2019-12-12 at 10 33 05](https://user-images.githubusercontent.com/16756389/70692228-edb19b00-1ccb-11ea-8587-0763b237c85e.png)

**Comment by barisegesevgili** [comment]
Thanks for reporting! I have checked it out and corrected the related problem. Solution PR will be merged to backend-dev as soon as reviewed , you can try it out later on. Pls inform if further problems exist. Here is the related PR: https://github.com/bounswe/bounswe2019group6/pull/264
