### ISSUE TITLE
[Frontend] Missing data on 20-day period currency values chart

### ISSUE THREAD

**Issue by enozcan** [bounswe/bounswe2019group6#270]
Hi all,

Looks like the chart below under `Money Currencies` section is not updated or constructed with the data fetched from backend. I wonder if this part is going to be removed or fixed.

<img width="1467" alt="Screen Shot 2019-12-14 at 01 02 55" src="https://user-images.githubusercontent.com/44522401/70835227-784de380-1e0d-11ea-9df2-366d876d1cc4.png">

**Comment by irmakguzey** [comment]
Hey @enozcan,
Thanks for pointing this out! 
This graph will be removed with the PR #271.  Both for the design and logic perspectives. :)

**Comment by irmakguzey** [comment]
With the #271 merged, I am closing this issue.
Thanks again for opening it. :)
