### ISSUE TITLE
Bug report for transaction endpoints

### ISSUE THREAD

**Issue by sadullahgultekin** [bounswe/bounswe2019group6#277]
Hi @enozcan ,

Currently I am using transaction endpoints, specifically `/transaction/user/{username}`. I am getting the results below. Transaction with transaction type "SELL" returns 0 as the amount all the time. Can you check weather there is a problem with backend or not?

![Screen Shot 2019-12-15 at 21 17 22](https://user-images.githubusercontent.com/16756389/70866961-f8488a80-1f80-11ea-969a-e8d842685f99.png)

**Comment by enozcan** [comment]
@burakikanyildiz can you take care of this?

**Comment by burakikanyildiz** [comment]
Hey @sadullahgultekin , currently I'm working on it. BRB in a couple of minutes.

**Comment by sadullahgultekin** [comment]
Thank you for quick response, it works now !
