### ISSUE TITLE
Fix precision of amounts

### ISSUE THREAD

**Issue by sadullahgultekin** [bounswe/bounswe2019group6#286]
In the "My Investments" and "Search Trading Equipment" pages, we show numbers with high precision to the user. We need to clip these values, into 4 digits after the comma.

**Comment by mstfalp** [comment]
Rather than fixing this on client in our database any data that includes a value of some kind of currency should be in Decimal.
For our needs I think `DECIMAL(15, 5)` or `DECIMAL(14, 4)` should be enough to store 1 billion.

**Comment by sadullahgultekin** [comment]
We can ask to our backend team. 
Hi @enozcan @burakikanyildiz @barisegesevgili,
What do you think about this issue, can we handle it on backend?

**Comment by sadullahgultekin** [comment]
We have done fixed it on client side!
