### ISSUE TITLE
Create logo

### ISSUE THREAD

**Issue by sadullahgultekin** [bounswe/bounswe2019group6#29]

**Comment by sezgineray** [comment]
![155171484337876816](https://user-images.githubusercontent.com/15183812/53945562-f0df8100-40d2-11e9-90e1-75978d3b4e79.png)
![screen shot 2019-03-04 at 18 38 44](https://user-images.githubusercontent.com/15183812/53945564-f0df8100-40d2-11e9-86d1-5afde00ae22f.png)
