### ISSUE TITLE
Article cannot be deleted when it has a comment or comments.

### ISSUE THREAD

**Issue by bwqr** [bounswe/bounswe2019group6#297]
**Describe the bug**
Attempting to delete a article which has a comment or comments will result in an error with constraint violoation.
**To Reproduce**
1. Create an article
2. Create a comment belongs to article
3. Try to delete the article

**Expected behavior**
Article should be deleted.

**Current behavior**
A constraint violation error arises.

**Possible Solution**
Check the article and comment models.

**Additional context**

**Comment by enozcan** [comment]
Thanks for reporting. Fixed on 5a4ece4.
