### ISSUE TITLE
Design Android mock-up scenario

### ISSUE THREAD

**Issue by enozcan** [bounswe/bounswe2019group6#30]
Deadline: 03/03/2019 23:59

**Comment by sezgineray** [comment]
![bernie_profile](https://user-images.githubusercontent.com/15183812/53945611-0a80c880-40d3-11e9-927b-f68e266c31fc.png)
![explore_page](https://user-images.githubusercontent.com/15183812/53945612-0b195f00-40d3-11e9-9acf-38f5de9cb6fc.png)
![login_page](https://user-images.githubusercontent.com/15183812/53945613-0b195f00-40d3-11e9-85fb-20b1cd939c73.png)
![profile_page](https://user-images.githubusercontent.com/15183812/53945615-0b195f00-40d3-11e9-98ca-9740c78e7222.png)
