### ISSUE TITLE
Create media folder under repo

### ISSUE THREAD

**Issue by enozcan** [bounswe/bounswe2019group6#34]
Create a particular folder for storing images used in the repository pages.

**Comment by enozcan** [comment]
Deadline 10.03.2019 @23:59

**Comment by bwqr** [comment]
To use medias inside the wiki, media folder created under resources folder. Users can inline medias by  using "https://raw.githubusercontent.com/bounswe/bounswe2019group6/master/resources/media/" link followed by media name.
