### ISSUE TITLE
Reviews&Modifications on the Mockup

### ISSUE THREAD

**Issue by barandenizkorkmaz** [bounswe/bounswe2019group6#38]
During the lecture, i realised that there doesn't exist "continue as a guest" option in the application mockup. Sadullah and Enes's mockups are okay, but the android version needs a tiny maintenance.

**Comment by sezgineray** [comment]
![Profile_Page_with_skip](https://user-images.githubusercontent.com/15183812/54144099-15718b00-443c-11e9-9ea2-99e888351053.png)
