### ISSUE TITLE
Reviewing MockUps

### ISSUE THREAD

**Issue by barandenizkorkmaz** [bounswe/bounswe2019group6#40]

**Comment by enozcan** [comment]
on mockup2:

Make predictions specific for each equipment
@enozcan

**Comment by burakikanyildiz** [comment]
on mockup1: 
Redesign prediction success rate section according to feedback 3.

**Comment by enozcan** [comment]
on mockup3:

* Remove recommendations

@sadullahgultekin

**Comment by sadullahgultekin** [comment]
on mockup3:

- write the words that have searched to the search bar

**Comment by uskudarli** [comment]
is this still open? 

So many DONEs :)

There is no description of the task.

question: Are all 5 assignees reviewing all mockups? What is the convention here? Will ask in person.

**Comment by sadullahgultekin** [comment]
In the meeting before the mockups, we decided to make 3 different mockups. And for each mockup we assigned one person. 

We should have written something in the description, but, because we talked it in the meeting, we skipped it. 

Yes, we have lots of DONE's, but still job is incomplete :)

**Comment by barandenizkorkmaz** [comment]
According to the feedback, to be able to draw attention at first glance, we opened a general issue. Then, specialized issues are opened so as to gain a deeper insight for assignees. Since every person working for user scenarios&mockups are responsible from seperated tasks, it's hard for everyone to follow what other assignees are currently doing unless the responsible person from one specific task has already finished. To enable that everyone follows easily if the overall mission is over, a general issue handles a basic communication task very effectively.

**Comment by sezgineray** [comment]
On mobile mock-up:
- DONE: Add follower & following and notifications icon on profile page
- DONE: Seperate prediction rates on profiles
- DONE: Replace mock content with real text
- DONE: Add new mock-ups
