### ISSUE TITLE
Expand mock-up 3 with more details

### ISSUE THREAD

**Issue by sadullahgultekin** [bounswe/bounswe2019group6#41]

**Comment by sadullahgultekin** [comment]
@burakyuksel0 

Can you rewrite the user story 3 more detailed

**Comment by burakyuksel0** [comment]
@sadullahgultekin I added some more steps. Can you review and edit the mock-up accordingly?

**Comment by sadullahgultekin** [comment]
@burakyuksel0 thank you for reviews, I edit the mockups. 

If you come up with any other revisions, I would be glad to hear them
