### ISSUE TITLE
Required Modifications For Class Diagram

### ISSUE THREAD

**Issue by sadullahgultekin** [bounswe/bounswe2019group6#44]
As we talked in the weekly meeting, we detected some functions and variables that should be added to class diagram. The arguments for the functions may not be correct, please check before adding to the diagram

* Trading Equipment Class
	- addTradingEquipmentToUserPortfolio(userId, tradingEquipment)
* Event Class
	- chaseEvent(userID)
* Registered User Class
	- methods
		- makeProfilePrivate()
		- makeProfilePublic()
		- editBio(string)
		- acceptFollowRequest(registeredUser)
		- declineFollowRequest(registeredUser)
	- variable
		- followers(<RegisterUser List>)
		- following(<RegisterUser List>)

There is also one function that should be deleted

* Registered User Class
	- getUserProfile()

**Comment by bwqr** [comment]
I reviewed your proposals about class diagram. imo, 

addTradingEquipmentToUserPortfolio method should belong to Portfolio class as addTradingEquipment, since there is no class UserPortfolio and Portfolio class contains the trading equipments.

For Event class, can you describe the chaseEvent method a little bit?

For Registered User class, instead of making special methods for actions -makeProfilePrivate, can we describe them as updateUser or updateProfile, and pass the public as a boolean variable?

**Comment by sadullahgultekin** [comment]
In sequence diagram, we want to make a diagram for "creation&edition in portfolio". Using the current functions in Portfolio Class, we can create/delete/update a portfolio. But we couldn't find a function to add new tradingEquipment to a portfolio that belongs to a user. I think the functionality that we want should be added to Trading Equipment Class, because after creating a portfolio, we don't have any business with Portfolio class. We only need a function that adds a trading equipment to a users portfolio.

We also want to make a diagram to follow an event. A user can make some searches using the Search Engine Class, but there isn't any function to follow it. We thought that, this function should be added to event class, and user should be able to use the result of the Search function to follow an Event. Maybe instead of using the word "chase", we can use "follow".

We can make one one function to make the profile public or private. But updateProfile is too general for a function name. Instead, changePrivacy can be used.

**Comment by bwqr** [comment]
You stated about users portfolio like user can have only one portfolio. However user can have more than one portfolio. With your method we have to define which portfolio to add trading equipment. That will create a confusion. I am still insisting on adding method to Portfolio class :) 

As I searched the requirements, I couldn't find anything about following an event, or am I missing it? Should we add it to requirements?

changePrivacy will do it.

**Comment by sadullahgultekin** [comment]
If you insist so, lets do it that way :) But we need a function to do that :) 

My bad, if we don't have any statement in requirements, you can ignore my suggestion :)

Thanks

**Comment by irmakguzey** [comment]
Necessary changes are made in the Class Diagram both according to the feedback we had and this issue. 
Thanks. :)
