### ISSUE TITLE
Revise Sequence Diagrams

### ISSUE THREAD

**Issue by enozcan** [bounswe/bounswe2019group6#45]
@sezgineray : 
Create sequence diagrams for:

* Sign Up
* Login with Email
* Login with Google
* Forgot password

@enozcan , @sadullahgultekin :
Update existing diagrams created last week.

**Comment by sadullahgultekin** [comment]
I revised my diagrams according to the feedback, I will upload them later to the repo

**Comment by sadullahgultekin** [comment]
@enozcan 
Can you create sequence diagrams for:

* Sign Up
* Forgot password

**Comment by enozcan** [comment]
Sure, for the sake of the group I do not hesitate to shoulder that responsibility. That's a team work, isn't it? We have to make up our other friends' irresponsibility.
