### ISSUE TITLE
Revise Use-Case Diagram, according to feedbacks

### ISSUE THREAD

**Issue by barisegesevgili** [bounswe/bounswe2019group6#46]
feedback:

-Searching by significance level feature is only available for events. 

-Adding register and log in in use case diagram

**Comment by burakikanyildiz** [comment]
I have edited use-case diagram:
-Added register and log in in use case diagram.
-Made proper modifications

**Comment by barisegesevgili** [comment]
-Searching by significance level feature is only available for events. --> SOLVED
