### ISSUE TITLE
Communication Plan & Requirements And Mockups

### ISSUE THREAD

**Issue by sadullahgultekin** [bounswe/bounswe2019group6#51]
Write the communication plan & requirements and mock-ups for milestone until 31.03.2019-11.59 AM

**Comment by burakikanyildiz** [comment]
1. Created and filled a LateX page for communication plan.
2. Created and filled a LateX page for Glossary and Requirements.
3. Created and filled a LateX page for Mock-ups.
to be put into Milestone#1.
Need to be reviewed.

**Comment by enozcan** [comment]
Ikan,

I just reviewed your work and I think it would be nice if you scaled the mobile mock up images in such a way there were 2 of them next to each other. So that they would take up less space on the report page.

**Comment by burakikanyildiz** [comment]
Enes,
Thanks for feedback.
Mockups were just modified according to your feedback. Now, they will look more elegant on report.
