### ISSUE TITLE
Write the code for Twitter API in Django env. 

### ISSUE THREAD

**Issue by enozcan** [bounswe/bounswe2019group6#65]
Until 04.05.2019 - 23:59

**Comment by sadullahgultekin** [comment]
I wrote the code for twitter api, but I need some initial twitter accounts to start crawling. @barisegesevgili can you find some for me?

**Comment by sadullahgultekin** [comment]
@bwqr twitterapp returns a JSON in the "/tweeternews" endpoint as follows.

The format: { 'list_of_links' : {list} }
list contains links of some economic events
example output: 
{
    all_links: [
    "https://go.shr.lc/2L9MKtJ",
    "https://www.publish0x.com/earning-crypto/what-are-security-tokens-and-stos-xllynk?a=mWZdPqweKg",
    "https://go.shr.lc/2VeKaGv",
    "http://bit.ly/2U1f8gz",
    "http://bit.ly/2U1Rb8Q",
    "http://bit.ly/2U37aUi",
    "http://bit.ly/2YUjhGS",
    "http://bit.ly/2U1f8gz",
    "http://bit.ly/2YQH0rv",
    "http://bit.ly/2U1RXmg",
    "https://www.publish0x.com/consensus-report/along-with-bitcos-prices-lightg-network-numbers-explod-xepzw?a=mWZdPqweKg",
    "https://www.publish0x.com/earning-crypto/3-risks-of-bitcoin-and-the-best-way-to-avoid-them-tips-from-the-experts-xepoq?a=mWZdPqweKg",
    "https://go.shr.lc/2Uqlvyo"
]
}
