### ISSUE TITLE
Write the code for articles & news API in Django env. 

### ISSUE THREAD

**Issue by enozcan** [bounswe/bounswe2019group6#67]
Until 04.05.2019 - 23:59

**Comment by burakyuksel0** [comment]
What does articles mean here? Are we expected to get articles from an external source?
I thought articles in our system are written by users.

**Comment by enozcan** [comment]
When we discussed that we thought there might be an article API service from platforms like Medium or sth. and we could use that in our app. However your claim seems reasonable and I think it's OK to serve news API only @burakyuksel0 . What's your opinion @barandenizkorkmaz  @barisegesevgili ?
