### ISSUE TITLE
Implement UI of the web page

### ISSUE THREAD

**Issue by enozcan** [bounswe/bounswe2019group6#68]
until 04.05.2019 - 23:59

**Comment by enozcan** [comment]
@bwqr The json data post to "/events" endpoint is as follows.
Please note:
- The dictionary in that format:  `{ name-of-event : {event-data} } `
- "rep" is used for importance, ranging from 1 to 3
-  values for "actual", "prev", "forecast" keys might be empty string for some events.

`{"US-China Trade Talks": {"county": "China", "date": "2019-04-30", "rep": 3, "actual": "", "prev": "", "forecast": ""}, "Unemployment Rate": {"county": "Macau", "date": "2019-04-30", "rep": 2, "actual": "1.7%", "prev": "1.7%", "forecast": "1.7%"}, "Non Manufacturing PMI": {"county": "China", "date": "2019-04-30", "rep": 2, "actual": "54.3", "prev": "54.8", "forecast": "54.2"}, "NBS Manufacturing PMI": {"county": "China", "date": "2019-04-30", "rep": 3, "actual": "50.1", "prev": "50.5", "forecast": "50.8"}, "ANZ Business Confidence": {"county": "New Zealand", "date": "2019-04-30", "rep": 1, "actual": "-37.5", "prev": "-38.0", "forecast": "-40"}, "PPI YoY": {"county": "Philippines", "date": "2019-04-30", "rep": 1, "actual": "3.6%", "prev": "2.6%", "forecast": "3.2%"}, "Private Sector Credit YoY": {"county": "Australia", "date": "2019-04-30", "rep": 2, "actual": "3.9%", "prev": "4.2%", "forecast": "4.3%"}, "Private Sector Credit MoM": {"county": "Australia", "date": "2019-04-30", "rep": 2, "actual": "0.3%", "prev": "0.3%", "forecast": "0.2%"}, "Caixin Manufacturing PMI": {"county": "China", "date": "2019-04-30", "rep": 3, "actual": "50.2", "prev": "50.8", "forecast": "51"}, "Bank Lending": {"county": "Singapore", "date": "2019-04-30", "rep": 1, "actual": "$676.1B", "prev": "$672.3B", "forecast": "$678B"}}`

**Comment by bwqr** [comment]
#79 , issue is closed.
