### ISSUE TITLE
Filling favourite repo page

### ISSUE THREAD

**Issue by enozcan** [bounswe/bounswe2019group6#7]
Fill the appropriate place reserved for you from [here](https://github.com/bounswe/bounswe2019group6/wiki/Repositories)

- [x] Barış Ege Sevgili
- [x] Sadullah Gültekin
- [x] Baran Deniz Korkmaz
- [x] Eray Sezgin
- [x] Burak Yüksel
- [x] Burak İkan Yildiz
- [x] Fatih Mustafa Kurt
- [x] Furkan Nane
- [x] Enes Turan Özcan
- [x] Irmak Güzey

**Comment by burakikanyildiz** [comment]
Added favourite repo to repo page.
