### ISSUE TITLE
Prepare the AWS and make the deployment of the system

### ISSUE THREAD

**Issue by sadullahgultekin** [bounswe/bounswe2019group6#71]
In this week, everyone will write their code, and push it to the repo. At the end, we need to make our work available in an Amazon Web Server.

**Comment by bwqr** [comment]
I have created an instance in aws, and enabled it for deployment. If your old server still runs perfectly, we could give a try about using it.

**Comment by sadullahgultekin** [comment]
I've just tried my old server, I think it is working fine, we can use whichever we want.

**Comment by sadullahgultekin** [comment]
We created our AWS instance from the account of @bwqr and got our ip
