### ISSUE TITLE
Add currency translations other than "From EUR" and make necessary UI modificitaions.

### ISSUE THREAD

**Issue by burakikanyildiz** [bounswe/bounswe2019group6#80]

**Comment by burakikanyildiz** [comment]
I have added 2 new feature. 'EURtoALL' and 'FromXtoY'. 
The first one is listing all currencies in terms of EUR. 
The latter one is returning any rate feature which was not included in the first version of currencyrateapp.
@bwqr Can you please implement front-end for those new features?

**Comment by burakyuksel0** [comment]
I noticed a bug while testing. In function **currency_rate_view()** within the file **currencyrateapp/views.py**, you are returning the response you get from target symbol in case of invalid input. However, this causes function to return a response with **success field** equal to **True** if target symbol is valid but source symbol is invalid.
I changed the implementation a little bit. Can you review and share your ideas?

**Comment by burakikanyildiz** [comment]
I have reviewed your implementation, it seems no flaw in your implementation. Also thanks for feedback and error correction @burakyuksel0 .
@bwqr Did you make necessary modifications for UI in compliance with new features? If so, we can open new pull request.

**Comment by bwqr** [comment]
I have not yet made necessary modification, since it requires lots of structural changes, yet I need your permission to make some changes to make displaying on ui easy .

**Comment by burakikanyildiz** [comment]
@bwqr Sure you can make necessary changes that help you to display on ui easy. Also if you wish and tell me about necessary changes, I can help you too.
