### ISSUE TITLE
Editting Personal Page

### ISSUE THREAD

**Issue by barandenizkorkmaz** [bounswe/bounswe2019group6#90]
Hello Mustafa,
Since you are our new team member, you're expected to create your personal repository page. I've just created page for you so that i could add the link into readme etc. We'd be glad if you edit your personal page when you are available, since the instructor cares about the updates in the repository.

**Comment by mstfalp** [comment]
Updated my page  and added small background on https://github.com/bounswe/bounswe2019group6/wiki/Mustafa-Alparslan
