### ISSUE TITLE
Searching and implementing Db connection in Spring Boot application

### ISSUE THREAD

**Issue by burakikanyildiz** [bounswe/bounswe2019group6#91]
Since Spring Boot application is going to be used as backend, all backend developers have to be get familiar with Spring Boot and its connection to database.

**Comment by barisegesevgili** [comment]
Using Python-Django duo, instead of Java-Spring should be considered again as it mentioned at today's presentation by Mr. Güler by Hipolab.

**Comment by enozcan** [comment]
Hi @barisegesevgili 

Django might be a good choice but I have almost no experience with this framework and AFAIK neither you both. Instead, if we use Spring in which I'm pretty experienced the implementation process would be easier and faster when I give you hints and guidance upon writing endpoints etc stuff. 

@burakikanyildiz what's your opinion about this?

**Comment by enozcan** [comment]
I think @burakikanyildiz is OK as well. A "very" base implementation is added on  93a0bb009bd7b460212fe2ef610fb130b3ffb369. Hence closing the issue.
