### ISSUE TITLE
Design register page layout 

### ISSUE THREAD

**Issue by mstfalp** [bounswe/bounswe2019group6#93]
Use the layout_register.xml to design a proper layout. Also implement the functionalities of buttons and validations of data entered. Give warning if provided data is not valid.

**Comment by bwqr** [comment]
https://github.com/bounswe/bounswe2019group6/commit/2b37b6a5f6108ce4456f42924c167ac9cdb2ff54 commit implements the Register Logic. Currently, warnings about inputs do their jobs poorly.
