### ISSUE TITLE
Following event endpoints and service

### ISSUE THREAD

**Issue by enozcan** [bounswe/bounswe2019group6#96]
- [x] Create endpoints for following / unfollowing other users
- [x] Create endpoints for getting follower / following lists
- [ ] Create accepting or declining following request facility for private profiles

**Comment by burakikanyildiz** [comment]
Create endpoints for following / unfollowing other users, and Create endpoints for getting follower / following lists functionalities are ready now in the backend-follow brach.

**Comment by enozcan** [comment]
implemented in #129
